apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: ts-react.com # We'll need to configure this host correctly in AWS. On Minikube, we can edit our /etc/hosts file
    http:
      paths:
        - path: # Most requests should go to our normal CRA
          backend:
            serviceName: ts-react
            servicePort: 80
        - path: /graphql # Requests to our /graphql endpoint should go to our API service, typeorm, running on port 1234
          backend:
            serviceName: typeorm
            servicePort: 1234
